<a href="https://colab.research.google.com/github/HemaGarima/Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
li = [1,2,3,4]
print(np.array(li))

[1 2 3 4]


In [3]:
tup = (5 , 6 , 7 , 8)
print(np.array(tup))

[5 6 7 8]


In [4]:
iterable = (a for a in range(8))
print(np.fromiter(iterable , float))

[0. 1. 2. 3. 4. 5. 6. 7.]


In [5]:
list_1 = [1 , 2 , 3 , 4]
list_2 = [5 , 6 , 7 , 8]
list_3 = [9 , 10 , 11 , 12]
print(np.array([list_1 , list_2 , list_3]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(np.empty([4,3] , dtype = int))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [8]:
print(np.linspace(1,10,3))

[ 1.   5.5 10. ]


In [9]:
print(np.zeros(5 , dtype = int))

[0 0 0 0 0]


In [10]:
print(np.ones(5 , dtype = int))

[1 1 1 1 1]


In [11]:
print(np.random.rand(5))

[0.30282708 0.32618854 0.0718954  0.50984304 0.04256863]


In [12]:
print(np.random.randint(5 , size = 10))

[1 4 0 4 0 4 0 0 3 3]


In [13]:
print(np.zeros([4,3] , dtype = np.int32))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
print(np.ones([4,3] , dtype = np.int32))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
print(np.full([2,2] , 67 , dtype = int))

[[67 67]
 [67 67]]


In [16]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [18]:
y = [1,2,3,4]
print(y)

[1, 2, 3, 4]


In [19]:
print(x.dtype)

int64


In [20]:
print(type(x))

<class 'numpy.ndarray'>


In [21]:
print(type(y))

<class 'list'>


In [22]:
%timeit [j**4 for j in range(1,9)]

3.04 µs ± 468 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%timeit np.arange(1,9)**4

3.54 µs ± 544 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
x = [1,2,3,4]
y = np.array(x)
print(y)

[1 2 3 4]


In [25]:
y = np.array([1,2,3,4,5])
print(y)

[1 2 3 4 5]


In [26]:
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [27]:
l = []
for i in range(1,5):
  int_1 = input("Enter : ")
  l.append(int_1)
print(np.array(l))

Enter : 3
Enter : 4
Enter : 5
Enter : 7
['3' '4' '5' '7']


In [28]:
ar2 = np.array([[1,2,3,4] , [1,2,3,4]])

In [29]:
print(ar2)

[[1 2 3 4]
 [1 2 3 4]]


In [30]:
print(ar2.ndim)

2


In [31]:
ar3 = np.array([[[1,2,3,4] , [1,2,3,4] , [1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [32]:
arn = np.array([1,2,3,4] , ndmin = 10)

In [33]:
print(arn)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [34]:
ar_zero = np.zeros(4)

In [35]:
print(ar_zero)

[0. 0. 0. 0.]


In [36]:
 ar_zero1 = np.zeros((3,4))
 print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [38]:
ar_emp = np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


In [39]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [40]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [42]:
ar_lin = np.linspace(0,10 , num = 5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [43]:
var = np.random.rand(4)
print(var)

[0.11428303 0.9273702  0.01462588 0.40790145]


In [44]:
var1 = np.random.rand(2,5) # generate random value between 0 to 1
print(var1)

[[0.3129878  0.12968919 0.11185834 0.40162764 0.53182674]
 [0.75562882 0.34607831 0.79090351 0.23194878 0.4140361 ]]


In [45]:
var2 = np.random.randn(5) # generate random value close to zero. May return positive or negative numbers as well.
print(var2)

[ 1.03645816  0.45255002  2.40778647 -0.78553688  0.78127258]


In [46]:
var3 = np.random.ranf(4) # Do random sampling in numpy , Returns an array of specified shape and fills it with random floats in the half open interval [0.0 , 1.0].
print(var3)

[0.16253851 0.19615126 0.14341139 0.08452603]


In [47]:
# randint() - the function is used to generate a random number between a given range

In [48]:
var4 = np.random.randint(5,20 ,5)
print(var4)

[16 18 11  8 15]


In [49]:
var = np.array([1,2,3,4,12 ,13 , 14 , 15])
print("Data Type : " , var.dtype)

Data Type :  int64


In [50]:
var = np.array([1.0 , 1.2 , 1.4])
print("Data Type : " , var.dtype)

Data Type :  float64


In [51]:
var = np.array(["a" , "s" , "d" , "f"])
print("Data Type : " , var.dtype)

Data Type :  <U1


In [52]:
var = np.array(["a" , "s" , "d" , "f" , 235])
print("Data Type : " , var.dtype)

Data Type :  <U21


In [53]:
x = np.array([1,2,3,4])
print("Data Type : " , x.dtype )

Data Type :  int64


In [54]:
x = np.array([1,2,3,4] , dtype = np.int8)
print("Data Type : " , x.dtype )

Data Type :  int8


In [55]:
x = np.array([1,2,3,4] , dtype = "f")
print("Data Type : " , x.dtype )
print(x)

Data Type :  float32
[1. 2. 3. 4.]


In [56]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)
print("Data Type : " , x2.dtype)
print("Data Type : " , new.dtype)
print("Data Type : " , new_one.dtype)
print(x2)
print(new)
print(new_one)

Data Type :  int64
Data Type :  float32
Data Type :  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [57]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [58]:
var = np.array([1,2,3,4])
varadd = var-3
print(varadd)

[-2 -1  0  1]


In [59]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [60]:
var = np.array([1,2,3,4])
varadd = var*3
print(varadd)

[ 3  6  9 12]


In [61]:
var = np.array([1,2,3,4])
varadd = var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [62]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1 , var2)
print(varadd)

[2 4 6 8]


In [63]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1 , 3)
print(varadd)

[4 5 6 7]


In [64]:
var = np.array([1,2,3,4])
varadd = var%3
print(varadd)

[1 2 0 1]


In [65]:
var21 = np.array([[1,2,3,4] , [1,2,3,4]])
var22 = np.array([[1,2,3,4] , [1,2,3,4]])
varadd2 = var21 + var22
print(var21)
print(var22)
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]
[[2 4 6 8]
 [2 4 6 8]]


In [66]:
var = np.array([1,2,3,4])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


In [67]:
var = np.array([1,2,3,4,5,3,2])
print("min : " , np.min(var) , "argmin : " , np.argmin(var))
print("max : " , np.max(var) , "argmax : " , np.argmax(var))

min :  1 argmin :  0
max :  5 argmax :  4


In [68]:
var1 = np.array([[2,1,3],[9,5,5]]) # axis = 0 --> column
# axis = 1 --> row
print(np.min(var1 , axis = 1))
print(np.min(var1 , axis = 0))

[1 5]
[2 1 3]


In [69]:
print("sqrt : " ,np.sqrt(var))

sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [70]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [71]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [72]:
var1 = np.array([1,2,3,4] , ndmin = 4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [73]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [74]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10 , 11 ,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)
print()
one = x1.reshape(-1) # to reshaping array in one dimension
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [75]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 