<a href="https://colab.research.google.com/github/HemaGarima/Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
li = [1,2,3,4]
print(np.array(li))

[1 2 3 4]


In [5]:
tup = (5 , 6 , 7 , 8)
print(np.array(tup))

[5 6 7 8]


In [6]:
iterable = (a for a in range(8))
print(np.fromiter(iterable , float))

[0. 1. 2. 3. 4. 5. 6. 7.]


In [7]:
list_1 = [1 , 2 , 3 , 4]
list_2 = [5 , 6 , 7 , 8]
list_3 = [9 , 10 , 11 , 12]
print(np.array([list_1 , list_2 , list_3]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(np.empty([4,3] , dtype = int))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [10]:
print(np.linspace(1,10,3))

[ 1.   5.5 10. ]


In [11]:
print(np.zeros(5 , dtype = int))

[0 0 0 0 0]


In [12]:
print(np.ones(5 , dtype = int))

[1 1 1 1 1]


In [13]:
print(np.random.rand(5))

[0.4632852  0.87593742 0.09997444 0.09550092 0.82244261]


In [14]:
print(np.random.randint(5 , size = 10))

[0 0 4 1 0 4 1 0 4 3]


In [15]:
print(np.zeros([4,3] , dtype = np.int32))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
print(np.ones([4,3] , dtype = np.int32))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
print(np.full([2,2] , 67 , dtype = int))

[[67 67]
 [67 67]]


In [19]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
